---
kubernetes_master_kubeadm_config:
  apiVersion: kubeadm.k8s.io/v1alpha1
  kind: MasterConfiguration
  kubernetesVersion: 1.10.8
  api:
    controlPlaneEndpoint: "{{ kubernetes_common_api_fqdn }}" # | kube_lookup_hostname(kubernetes_common_api_fqdn) }}"
  apiServerExtraArgs:
    "endpoint-reconciler-type": "lease"
  apiServerCertSANs: "{{ kubernetes_common_api_ip | kube_lookup_hostname(kubernetes_common_api_fqdn, True) }}"
  etcd:
    endpoints: "{{ etcd_client_endpoints }}"
