---
kubernetes_master_kubeadm_config:
  kubernetesVersion: 1.11.3
  api:
    advertiseAddress: "{{ kubernetes_common_api_ip | kube_lookup_hostname(kubernetes_common_api_fqdn) }}"
  apiServerExtraArgs:
    "endpoint-reconciler-type": "lease"
  apiServerCertSANs: "{{ kubernetes_common_api_ip | kube_lookup_hostname(kubernetes_common_api_fqdn, True) }}"
  etcd:
    endpoints: "{{ etcd_client_endpoints }}"
