---
- name: add the kubernetes apt repo key
  apt_key:
    url: "{{ kubernetes_apt_key_url }}"
    state: present
  retries: 5
  delay: 5

- name: add the kubernetes apt repo
  apt_repository:
    repo: "{{ kubernetes_apt_repo_string }}"
    update_cache: True
    state: present
  retries: 5
  delay: 5

- name: install kubernetes packages
  apt:
    name:
      - "kubelet={{ kubernetes_version | kube_platform_version('debian') }}"
      - "kubeadm={{ kubernetes_version | kube_platform_version('debian') }}"
      - "kubectl={{ kubernetes_version | kube_platform_version('debian') }}"
      - "kubernetes-cni={{kubernetes_cni_version | kube_platform_version('debian') }}"
  retries: 5
  delay: 5
